#!/bin/sh
set -eu

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_root"

fail() {
  printf 'agent harness interface check failed: %s\n' "$*" >&2
  exit 1
}

for required_file in \
  .ai-first.toml \
  .ai-first.lock \
  .ai-first/check.py \
  .ai-first/overlays/agents-first-read.md \
  .ai-first/overlays/agents-project.md \
  .ai-first/overlays/harness-project.md \
  AGENTS.md \
  docs/agent-harness.md \
  scripts/check-publication-boundary.py; do
  [ -s "$required_file" ] || fail "missing or empty $required_file"
done

for generated_file in AGENTS.md docs/agent-harness.md; do
  grep -Fq -- '<!-- Generated by ai-first 1.2.0.' "$generated_file" ||
    fail "$generated_file generated boundary is missing"
done

expected_agents_headings=$(cat <<'HEADINGS'
## First Read
## AI-first Core Contract
## Repository Overlay
HEADINGS
)
actual_agents_headings=$(sed -n 's/^\(## .*\)$/\1/p' AGENTS.md)
[ "$actual_agents_headings" = "$expected_agents_headings" ] ||
  fail "AGENTS.md section order differs from ai-first bootstrap map"

for required_line in \
  '- Structure ID: `ai-first-harness-v1`.' \
  '- Framework version: `1.2.0`.' \
  '- Project: `fdiff`.' \
  '- Publication class: `public`.' \
  '- Generated drift check: `python3 .ai-first/check.py`.'; do
  grep -Fq -- "$required_line" docs/agent-harness.md ||
    fail "docs/agent-harness.md is missing: $required_line"
done

expected_harness_headings=$(cat <<'HEADINGS'
## Interface
## Project Objective
## Core Operating Contract
## Execution Loop
## Verification And Evidence
## Escalation
## VCS And Publish
## Harness Evaluation And Improvement
## Capability Profiles
## Project Overlay
## Related Documents
HEADINGS
)
actual_harness_headings=$(sed -n 's/^\(## .*\)$/\1/p' docs/agent-harness.md)
[ "$actual_harness_headings" = "$expected_harness_headings" ] ||
  fail "docs/agent-harness.md section order differs from ai-first-harness-v1"

expected_profile_headings=$(cat <<'HEADINGS'
### Capability Profile: vcs-jj
### Capability Profile: public-repository
### Capability Profile: openai-agent-guidance
HEADINGS
)
actual_profile_headings=$(sed -n 's/^\(### Capability Profile: .*\)$/\1/p' AGENTS.md)
[ "$actual_profile_headings" = "$expected_profile_headings" ] ||
  fail "AGENTS.md capability profile order differs from .ai-first.toml"

python3 - <<'PY'
import json
from pathlib import Path

lock = json.loads(Path(".ai-first.lock").read_text(encoding="utf-8"))
framework = lock.get("framework", {})
expected = {
    "version": "1.2.0",
    "source_kind": "release",
    "source_revision": "v1.2.0",
    "source_commit": "3db2810c82d0dbab3988f3fbd77ed59bb447a9cb",
}
for key, value in expected.items():
    if framework.get(key) != value:
        raise SystemExit(f"agent harness interface check failed: lock {key} mismatch")
PY

python3 .ai-first/check.py
scripts/check-publication-boundary.py

printf 'agent harness interface is valid: ai-first-harness-v1 / fdiff overlay\n'
